// Code generated by codegen; DO NOT EDIT.

package binaryauthorization

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/binaryauthorization/apiv1/binaryauthorizationpb"
)

func createAttestors(gsrv *grpc.Server) error {
	fakeServer := &fakeAttestorsServer{}
	pb.RegisterBinauthzManagementServiceV1Server(gsrv, fakeServer)
	return nil
}

type fakeAttestorsServer struct {
	pb.UnimplementedBinauthzManagementServiceV1Server
}

func (f *fakeAttestorsServer) ListAttestors(context.Context, *pb.ListAttestorsRequest) (*pb.ListAttestorsResponse, error) {
	resp := pb.ListAttestorsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestAttestors(t *testing.T) {
	client.MockTestGrpcHelper(t, Attestors(), createAttestors, client.TestOptions{})
}
