// Code generated by codegen; DO NOT EDIT.

package accesscontextmanager

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/accesscontextmanager/apiv1/accesscontextmanagerpb"
)

func createAccessLevels(gsrv *grpc.Server) error {
	fakeServer := &fakeAccessLevelsServer{}
	pb.RegisterAccessContextManagerServer(gsrv, fakeServer)
	return nil
}

type fakeAccessLevelsServer struct {
	pb.UnimplementedAccessContextManagerServer
}

func (f *fakeAccessLevelsServer) ListAccessPolicies(context.Context, *pb.ListAccessPoliciesRequest) (*pb.ListAccessPoliciesResponse, error) {
	resp := pb.ListAccessPoliciesResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestAccessLevels(t *testing.T) {
	client.MockTestGrpcHelper(t, AccessLevels(), createAccessLevels, client.TestOptions{})
}
