// Code generated by codegen; DO NOT EDIT.

package accesscontextmanager

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/accesscontextmanager/apiv1/accesscontextmanagerpb"
)

func createUserAccessBindings(gsrv *grpc.Server) error {
	fakeServer := &fakeUserAccessBindingsServer{}
	pb.RegisterAccessContextManagerServer(gsrv, fakeServer)
	return nil
}

type fakeUserAccessBindingsServer struct {
	pb.UnimplementedAccessContextManagerServer
}

func (f *fakeUserAccessBindingsServer) ListGcpUserAccessBindings(context.Context, *pb.ListGcpUserAccessBindingsRequest) (*pb.ListGcpUserAccessBindingsResponse, error) {
	resp := pb.ListGcpUserAccessBindingsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestUserAccessBindings(t *testing.T) {
	client.MockTestGrpcHelper(t, UserAccessBindings(), createUserAccessBindings, client.TestOptions{})
}
