// Code generated by codegen; DO NOT EDIT.

package accessapproval

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/accessapproval/apiv1/accessapprovalpb"
)

func createRequests(gsrv *grpc.Server) error {
	fakeServer := &fakeRequestsServer{}
	pb.RegisterAccessApprovalServer(gsrv, fakeServer)
	return nil
}

type fakeRequestsServer struct {
	pb.UnimplementedAccessApprovalServer
}

func (f *fakeRequestsServer) ListApprovalRequests(context.Context, *pb.ListApprovalRequestsMessage) (*pb.ListApprovalRequestsResponse, error) {
	resp := pb.ListApprovalRequestsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestRequests(t *testing.T) {
	client.MockTestGrpcHelper(t, Requests(), createRequests, client.TestOptions{})
}
