// Code generated by codegen; DO NOT EDIT.

package aiplatform

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/aiplatform/apiv1/aiplatformpb"
)

func createRequests(gsrv *grpc.Server) error {
	fakeServer := &fakeRequestsServer{}
	pb.RegisterDatasetServiceServer(gsrv, fakeServer)
	return nil
}

type fakeRequestsServer struct {
	pb.UnimplementedDatasetServiceServer
}

func (f *fakeRequestsServer) ListDatasets(context.Context, *pb.ListDatasetsRequest) (*pb.ListDatasetsResponse, error) {
	resp := pb.ListDatasetsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestRequests(t *testing.T) {
	client.MockTestGrpcHelper(t, Requests(), createRequests, client.TestOptions{})
}
