// Code generated by codegen; DO NOT EDIT.

package asset

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/asset/apiv1/assetpb"
)

func createAssets(gsrv *grpc.Server) error {
	fakeServer := &fakeAssetsServer{}
	pb.RegisterAssetServiceServer(gsrv, fakeServer)
	return nil
}

type fakeAssetsServer struct {
	pb.UnimplementedAssetServiceServer
}

func (f *fakeAssetsServer) ListAssets(context.Context, *pb.ListAssetsRequest) (*pb.ListAssetsResponse, error) {
	resp := pb.ListAssetsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestAssets(t *testing.T) {
	client.MockTestGrpcHelper(t, Assets(), createAssets, client.TestOptions{})
}
