// Code generated by codegen; DO NOT EDIT.

package cloudbuild

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "google.golang.org/genproto/googleapis/devtools/cloudbuild/v1"
)

func createWorkerPools(gsrv *grpc.Server) error {
	fakeServer := &fakeWorkerPoolsServer{}
	pb.RegisterCloudBuildServer(gsrv, fakeServer)
	return nil
}

type fakeWorkerPoolsServer struct {
	pb.UnimplementedCloudBuildServer
}

func (f *fakeWorkerPoolsServer) ListWorkerPools(context.Context, *pb.ListWorkerPoolsRequest) (*pb.ListWorkerPoolsResponse, error) {
	resp := pb.ListWorkerPoolsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestWorkerPools(t *testing.T) {
	client.MockTestGrpcHelper(t, WorkerPools(), createWorkerPools, client.TestOptions{})
}
