// Code generated by codegen; DO NOT EDIT.

package assuredworkloads

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/assuredworkloads/apiv1/assuredworkloadspb"
)

func createWorkloads(gsrv *grpc.Server) error {
	fakeServer := &fakeWorkloadsServer{}
	pb.RegisterAssuredWorkloadsServiceServer(gsrv, fakeServer)
	return nil
}

type fakeWorkloadsServer struct {
	pb.UnimplementedAssuredWorkloadsServiceServer
}

func (f *fakeWorkloadsServer) ListWorkloads(context.Context, *pb.ListWorkloadsRequest) (*pb.ListWorkloadsResponse, error) {
	resp := pb.ListWorkloadsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestWorkloads(t *testing.T) {
	client.MockTestGrpcHelper(t, Workloads(), createWorkloads, client.TestOptions{})
}
