// Code generated by codegen; DO NOT EDIT.

package clouddms

import (
	"context"
	"google.golang.org/api/iterator"

	pb "cloud.google.com/go/clouddms/apiv1/clouddmspb"

	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/cloudquery/plugins/source/gcp/client"

	"cloud.google.com/go/clouddms/apiv1"
)

func ConnectionProfiles() *schema.Table {
	return &schema.Table{
		Name:      "gcp_clouddms_connection_profiles",
		Resolver:  fetchConnectionProfiles,
		Multiplex: client.ProjectMultiplex,
		Columns: []schema.Column{
			{
				Name:     "project_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveProject,
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "create_time",
				Type:     schema.TypeTimestamp,
				Resolver: client.ResolveProtoTimestamp("CreateTime"),
			},
			{
				Name:     "update_time",
				Type:     schema.TypeTimestamp,
				Resolver: client.ResolveProtoTimestamp("UpdateTime"),
			},
			{
				Name:     "labels",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Labels"),
			},
			{
				Name:     "state",
				Type:     schema.TypeString,
				Resolver: client.ResolveProtoEnum("State"),
			},
			{
				Name:     "display_name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("DisplayName"),
			},
			{
				Name:     "error",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Error"),
			},
			{
				Name:     "provider",
				Type:     schema.TypeString,
				Resolver: client.ResolveProtoEnum("Provider"),
			},
		},
	}
}

func fetchConnectionProfiles(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)
	req := &pb.ListConnectionProfilesRequest{}
	gcpClient, err := clouddms.NewDataMigrationClient(ctx, c.ClientOptions...)
	if err != nil {
		return err
	}
	it := gcpClient.ListConnectionProfiles(ctx, req, c.CallOptions...)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return err
		}

		res <- resp

	}
	return nil
}
