// Code generated by codegen; DO NOT EDIT.

package clouddms

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/clouddms/apiv1/clouddmspb"
)

func createConnectionProfiles(gsrv *grpc.Server) error {
	fakeServer := &fakeConnectionProfilesServer{}
	pb.RegisterDataMigrationServiceServer(gsrv, fakeServer)
	return nil
}

type fakeConnectionProfilesServer struct {
	pb.UnimplementedDataMigrationServiceServer
}

func (f *fakeConnectionProfilesServer) ListConnectionProfiles(context.Context, *pb.ListConnectionProfilesRequest) (*pb.ListConnectionProfilesResponse, error) {
	resp := pb.ListConnectionProfilesResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestConnectionProfiles(t *testing.T) {
	client.MockTestGrpcHelper(t, ConnectionProfiles(), createConnectionProfiles, client.TestOptions{})
}
