// Code generated by codegen; DO NOT EDIT.

package clouddms

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/clouddms/apiv1/clouddmspb"
)

func createMigrationJobs(gsrv *grpc.Server) error {
	fakeServer := &fakeMigrationJobsServer{}
	pb.RegisterDataMigrationServiceServer(gsrv, fakeServer)
	return nil
}

type fakeMigrationJobsServer struct {
	pb.UnimplementedDataMigrationServiceServer
}

func (f *fakeMigrationJobsServer) ListMigrationJobs(context.Context, *pb.ListMigrationJobsRequest) (*pb.ListMigrationJobsResponse, error) {
	resp := pb.ListMigrationJobsResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestMigrationJobs(t *testing.T) {
	client.MockTestGrpcHelper(t, MigrationJobs(), createMigrationJobs, client.TestOptions{})
}
