// Code generated by codegen; DO NOT EDIT.

package apigeeregistry

import (
	"context"
	"google.golang.org/api/iterator"

	pb "google.golang.org/genproto/googleapis/cloud/apigeeregistry/v1"

	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/cloudquery/plugins/source/gcp/client"

	"cloud.google.com/go/apigeeregistry/apiv1"
)

func Apis() *schema.Table {
	return &schema.Table{
		Name:      "gcp_apigeeregistry_apis",
		Resolver:  fetchApis,
		Multiplex: client.ProjectMultiplex,
		Columns: []schema.Column{
			{
				Name:     "project_id",
				Type:     schema.TypeString,
				Resolver: client.ResolveProject,
			},
			{
				Name:     "name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Name"),
			},
			{
				Name:     "display_name",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("DisplayName"),
			},
			{
				Name:     "description",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Description"),
			},
			{
				Name:     "create_time",
				Type:     schema.TypeTimestamp,
				Resolver: client.ResolveProtoTimestamp("CreateTime"),
			},
			{
				Name:     "update_time",
				Type:     schema.TypeTimestamp,
				Resolver: client.ResolveProtoTimestamp("UpdateTime"),
			},
			{
				Name:     "availability",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("Availability"),
			},
			{
				Name:     "recommended_version",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("RecommendedVersion"),
			},
			{
				Name:     "recommended_deployment",
				Type:     schema.TypeString,
				Resolver: schema.PathResolver("RecommendedDeployment"),
			},
			{
				Name:     "labels",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Labels"),
			},
			{
				Name:     "annotations",
				Type:     schema.TypeJSON,
				Resolver: schema.PathResolver("Annotations"),
			},
		},
	}
}

func fetchApis(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)
	req := &pb.ListApisRequest{}
	gcpClient, err := apigeeregistry.NewRegistryClient(ctx, c.ClientOptions...)
	if err != nil {
		return err
	}
	it := gcpClient.ListApis(ctx, req)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return err
		}

		res <- resp

	}
	return nil
}
