// Code generated by codegen; DO NOT EDIT.

package artifactregistry

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/artifactregistry/apiv1/artifactregistrypb"
)

func createDockerimages(gsrv *grpc.Server) error {
	fakeServer := &fakeDockerimagesServer{}
	pb.RegisterArtifactRegistryServer(gsrv, fakeServer)
	return nil
}

type fakeDockerimagesServer struct {
	pb.UnimplementedArtifactRegistryServer
}

func (f *fakeDockerimagesServer) ListDockerImages(context.Context, *pb.ListDockerImagesRequest) (*pb.ListDockerImagesResponse, error) {
	resp := pb.ListDockerImagesResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestDockerimages(t *testing.T) {
	client.MockTestGrpcHelper(t, Dockerimages(), createDockerimages, client.TestOptions{})
}
