// Code generated by codegen; DO NOT EDIT.

package artifactregistry

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/artifactregistry/apiv1/artifactregistrypb"
)

func createPackages(gsrv *grpc.Server) error {
	fakeServer := &fakePackagesServer{}
	pb.RegisterArtifactRegistryServer(gsrv, fakeServer)
	return nil
}

type fakePackagesServer struct {
	pb.UnimplementedArtifactRegistryServer
}

func (f *fakePackagesServer) ListPackages(context.Context, *pb.ListPackagesRequest) (*pb.ListPackagesResponse, error) {
	resp := pb.ListPackagesResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestPackages(t *testing.T) {
	client.MockTestGrpcHelper(t, Packages(), createPackages, client.TestOptions{})
}
