// Code generated by codegen; DO NOT EDIT.

package artifactregistry

import (
	"context"
	"fmt"
	"github.com/cloudquery/plugin-sdk/faker"
	"github.com/cloudquery/plugins/source/gcp/client"
	"google.golang.org/grpc"
	"testing"

	pb "cloud.google.com/go/artifactregistry/apiv1/artifactregistrypb"
)

func createRepostiories(gsrv *grpc.Server) error {
	fakeServer := &fakeRepostioriesServer{}
	pb.RegisterArtifactRegistryServer(gsrv, fakeServer)
	return nil
}

type fakeRepostioriesServer struct {
	pb.UnimplementedArtifactRegistryServer
}

func (f *fakeRepostioriesServer) ListRepositories(context.Context, *pb.ListRepositoriesRequest) (*pb.ListRepositoriesResponse, error) {
	resp := pb.ListRepositoriesResponse{}
	if err := faker.FakeObject(&resp); err != nil {
		return nil, fmt.Errorf("failed to fake data: %w", err)
	}
	resp.NextPageToken = ""
	return &resp, nil
}

func TestRepostiories(t *testing.T) {
	client.MockTestGrpcHelper(t, Repostiories(), createRepostiories, client.TestOptions{})
}
